# Generated by Django 3.0.7 on 2020-11-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, default=1, null=True)),
                ('nipeg', models.CharField(default='', max_length=100)),
                ('nama', models.CharField(default='', max_length=100)),
                ('unit', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('noHp', models.CharField(default='', max_length=255)),
                ('numUnit', models.CharField(blank=True, default='', max_length=50)),
                ('num', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
