# Generated by Django 3.0.7 on 2020-11-08 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, default=1, null=True)),
                ('nipeg', models.CharField(default='', max_length=100)),
                ('nama', models.CharField(default='', max_length=255)),
                ('nomorPLT', models.CharField(default='', max_length=100)),
                ('tglPLT', models.CharField(default='', max_length=255)),
                ('jabatanTanpaPLT', models.CharField(default='', max_length=255)),
                ('jabatanPLT', models.CharField(default='', max_length=255)),
                ('terkirim', models.BooleanField(default=False)),
                ('email', models.CharField(default='', max_length=255)),
                ('noHp', models.CharField(default='', max_length=255)),
                ('peg', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegawai.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='mutasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, default=1, null=True)),
                ('nipeg', models.CharField(default='', max_length=100)),
                ('nama', models.CharField(default='', max_length=255)),
                ('jabatanSekarang', models.CharField(default='', max_length=255)),
                ('grade', models.CharField(default='', max_length=255)),
                ('tglJabTer', models.CharField(default='', max_length=255)),
                ('PendidikanTer', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('jabatanBaru', models.CharField(default='', max_length=255)),
                ('keterangan', models.CharField(default='', max_length=255)),
                ('noSk', models.CharField(default='', max_length=255)),
                ('tglSk', models.CharField(default='', max_length=255)),
                ('tglBerlaku', models.CharField(default='', max_length=255)),
                ('unit', models.CharField(default='', max_length=255)),
                ('jenjang', models.CharField(default='', max_length=255)),
                ('terkirim', models.BooleanField(default=False)),
                ('email', models.CharField(default='', max_length=255)),
                ('noHp', models.CharField(default='', max_length=255)),
                ('peg', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegawai.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='aps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, default=1, null=True)),
                ('nipeg', models.CharField(default='', max_length=100)),
                ('nama', models.CharField(default='', max_length=255)),
                ('jabatanSekarang', models.CharField(default='', max_length=255)),
                ('grade', models.CharField(default='', max_length=255)),
                ('tglJabTer', models.CharField(default='', max_length=255)),
                ('PendidikanTer', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('jabatanBaru', models.CharField(default='', max_length=255)),
                ('keterangan', models.CharField(default='', max_length=255)),
                ('noSk', models.CharField(default='', max_length=255)),
                ('tglSk', models.CharField(default='', max_length=255)),
                ('tglBerlaku', models.CharField(default='', max_length=255)),
                ('unitLama', models.CharField(default='', max_length=255)),
                ('unitPengirim', models.CharField(default='', max_length=255)),
                ('noPengirim', models.CharField(default='', max_length=255)),
                ('unitPenerima', models.CharField(default='', max_length=255)),
                ('noPenerima', models.CharField(default='', max_length=255)),
                ('terkirim', models.BooleanField(default=False)),
                ('email', models.CharField(default='', max_length=255)),
                ('noHp', models.CharField(default='', max_length=255)),
                ('peg', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegawai.pegawai')),
            ],
        ),
    ]
